### PR TITLE
Wechat qrcode module refinement

### PR DESCRIPTION
**Pull request by dddzg**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

```
force_builders=Custom
buildworker:Custom=linux-4,linux-6
build_image:Custom=ubuntu:20.04
```

### CODE REVIEW

**Comment by dddzg** [comment]
As mentioned in #2821 , there are some Future TODO (e.g. using cv::kmeans(),cvRound()). We will refine the code in this pr.

**Comment by dddzg** [comment]
Hi,@alalek . May I have your advice about the code before it megerd into official OpenCV?

**Review by alalek — COMMENTED** [review]
Thank you! In general changes look good to me.

> cv::kmeans()

Do you observe some issues with OpenCV implementation?

**Comment by dddzg** [comment]
The kmeans from OpenCV implementation is well. However, It has different parameters and different data structures with our implementation. As we can see, our code of kmeans is short. So, it may be complicated that we convert our `vector<vector<double>>` into OpenCV InputArray, defining distance function and apply OpenCV kmeans. Then, we convert back OutputArray into our `vector<Cluster>`. Could we preserve our kmeans?

**Review by alalek — APPROVED** [review]
Looks good to me! Thank you :+1:

**Comment by philp123** [comment]
There's a bug in unicomblock.cpp  "void UnicomBlock::Bfs(int y, int x)"  method. There's no bound check in 
112                  m_vcIndex[iPosition] = m_iNowIdx;

And when I test the image below, it causes the wechat qrcode engine to crash.

**Comment by Miracle2333** [comment]
> There's a bug in unicomblock.cpp "void UnicomBlock::Bfs(int y, int x)" method. There's no bound check in line 113
> 112 m_vcIndex[iPosition] = m_iNowIdx;
> 113 m_vcQueue[iTail++] = iNextY << 16 | iNextX;
> Which means when I debug the image below, it turns out that iTail > m_vcQueue.size(), and this out of bound error causes the
> program crash.
> 
> 

any refinement on this issue? i guess i got the same "segment fault" problem

**Comment by Miracle2333** [comment]
> There's a bug in unicomblock.cpp "void UnicomBlock::Bfs(int y, int x)" method. There's no bound check in line 113
> 112 m_vcIndex[iPosition] = m_iNowIdx;
> 113 m_vcQueue[iTail++] = iNextY << 16 | iNextX;
> Which means when I debug the image below, it turns out that iTail > m_vcQueue.size(), and this out of bound error causes the
> program crash.
> 
> 

i solved this problem temporarily by making the input smaller. Just resize the input image to a smaller dim (800 * 800). The detection results could be re-projected to the original image dim based on the resizing ratio and pading size.

From my side, this method could get right results of your image.

**Comment by philp123** [comment]
> > There's a bug in unicomblock.cpp "void UnicomBlock::Bfs(int y, int x)" method. There's no bound check in line 113
> > 112 m_vcIndex[iPosition] = m_iNowIdx;
> > 113 m_vcQueue[iTail++] = iNextY << 16 | iNextX;
> > Which means when I debug the image below, it turns out that iTail > m_vcQueue.size(), and this out of bound error causes the
> > program crash.
> > 
> 
> i solved this problem temporarily by making the input smaller. Just resize the input image to a smaller dim (800 * 800). The detection results could be re-projected to the original image dim based on the resizing ratio and pading size.
> 
> From my side, this method could get right results of your image.

Code has been updated, please check https://github.com/opencv/opencv_contrib/pull/2972

**Pull request merged**
