### PR TITLE
Implementation of PCT signature extractor (position-color-texture)

### PR DESCRIPTION
**Pull request by GregorKovalcik**
### This pullrequest implements PCT (position-color-texture) signature extractor and SQFD (signature quadratic form distance) evaluation of these signatures.

References:
Martin Krulis, Jakub Lokoc, Tomas Skopal.
Efficient Extraction of Clustering-Based Feature Signatures Using GPU Architectures.
Multimedia tools and applications, 75(13), pp.: 8071–8103, Springer, ISSN: 1380-7501, 2016
http://link.springer.com/article/10.1007/s11042-015-2726-y

Christian Beecks, Merih Seran Uysal, Thomas Seidl.
Signature quadratic form distance.
In Proceedings of the ACM International Conference on Image and Video Retrieval, pages 438-445. ACM, 2010.
http://dl.acm.org/citation.cfm?id=1816105

pct_signatures

### CODE REVIEW

**Comment by sovrasov** [comment]
@GregorKovalcik can you resolve the merge conflict please?

**Comment by GregorKovalcik** [comment]
@sovrasov Thank you for the notice. The conflicts were resolved.

**Comment by sovrasov** [comment]
@GregorKovalcik  We decided to integrate your PR, so please resolve the new merge conflict.

**Comment by GregorKovalcik** [comment]
@sovrasov Thank you. 

I did the merge, however, there were no merge conflicts.

**Comment by sovrasov** [comment]
Sorry for delay. Since the last commit is useless please, delete it and, you'll get +1 from me.

**Comment by GregorKovalcik** [comment]
I can delete all merge commits and leave just the first one, to keep a clean git history, if it is not a problem (I know it is a bad practice to delete commits).

**Comment by sovrasov** [comment]
It's ok, you can do whatever you like with your commits in your branch. The first priority for us is a clean history.

**Comment by GregorKovalcik** [comment]
I am sorry I closed this pull request accidentally. Please continue with the new one: #847

**Pull request closed without merging**
