### PR TITLE
CMake: fix ios build

### PR DESCRIPTION
**Pull request by alalek**
**Merge with main repo**: https://github.com/opencv/opencv/pull/7457

### CODE REVIEW

**Comment by rusuvalentin** [comment]
Hi! this will resolve the QTKit issue and error: use of undeclared identifier 'hal' ? I am new here and i don't really understand how this work.I have used git checkout pr7266 and now i don't have anymore QTKit issue,but i have the undeclared identifier 'hal' issue...

**Comment by mshabunin** [comment]
:+1:

**Comment by mshabunin** [comment]
@rusuvalentin , you should use corresponding versions of _opencv_ and _opencv_contrib_. Try to checkout _master_ version of both repositories and do clean build (in empty build directory).

**Comment by rusuvalentin** [comment]
@mshabunin  ,i don't really understand how...When i use git checkout 3.1.0 on both i have the same error.If i dont' i have fatal error: 'Python.h' file not found

**Comment by mshabunin** [comment]
@rusuvalentin , please try to ask question on http://answers.opencv.org

**Comment by rusuvalentin** [comment]
@mshabunin  ok,sorry,but i m new here.i will delete my questions

**Pull request merged**
