### PR TITLE
CUDA: disable code using obsolete objdetect API

### PR DESCRIPTION
**Pull request by alalek**
To fix CUDA build.
Related tests are disabled too.

```
force_builders=Custom
docker_image:Custom=ubuntu-cuda:16.04
```

### CODE REVIEW

**Comment by alalek** [comment]
:+1:

**Comment by xsacha** [comment]
How are we meant to do cv::cuda::CascadeClassifier now?

**Comment by alalek** [comment]
Feel free to prepare patch with migration of disabled code from removed legacy API and validate proposed changes.

**Comment by xsacha** [comment]
If it is replaced by something, what is the new API?

**Comment by alalek** [comment]
`cvLoad` -> `FileStorage`

**Comment by xsacha** [comment]
To replace detectMultiScale?

**Comment by isgursoy** [comment]
@alalek FileStorage accepting ::create is also disabled and throws.

**Comment by Mekhak** [comment]
So what is the alternative API for cuda::CascadeClassifier?

**Comment by xsacha** [comment]
From what I've deduced, it appears OpenVINO is what they want us to use now.
Intel exerting some influence?

**Pull request merged**
