### PR TITLE
aruco: correct marker coordinates in drawPlanarBoard

### LINKED ISSUE #592: Aruco: Charuco board markers are imprecise
The Charuco board code uses several image scaling and warping steps to create the final board image. Along the way, pixel precision gets lost. Creating a Charuco board with just as many pixels as are needed to place all markers will show that some markers are one row/column too small. Also with really large image sizes, the differences between the markers' square sizes are noticeable.

### PR DESCRIPTION
**Pull request by paroj**
see #788. fixes #592.

### CODE REVIEW

**Comment by sovrasov** [comment]
:+1:

**Comment by sovrasov** [comment]
I think this approach is preferable because it covers more usecases even if they seems to be non-realistic.

**Comment by sergarrido** [comment]
Maybe you could check if marker is parallel to image axis or not, and depending on that use INTER_NEAREST or a different interpolation approach.

**Comment by paroj** [comment]
> Maybe you could check if marker is parallel to image axis or not, and depending on that use INTER_NEAREST or a different interpolation approach.

this will break the `borderValue` hack used for masking. I still think that supporting rotated markers is more trouble than its worth..

**Comment by paroj** [comment]
done. `BORDER_TRANSPARENT` did the trick

**Comment by sovrasov** [comment]
@paroj thanks for patch! :+1: again

**Pull request merged**
