### PR TITLE
Added automatically generated C bindings and raw Haskell bindings.

### PR DESCRIPTION
**Pull request by arjuncomar**
This pull request is based on advice from [this](https://github.com/Itseez/opencv/pull/1600) pull request. This PR adds automatically generated C bindings that mirror the C++ API and raw Haskell bindings that map onto those C bindings. Please see the description in the linked PR for full details.

### CODE REVIEW

**Comment by arjuncomar** [comment]
Sorry about the delay in responding, this got lost with the holidays and
what not.

It's been almost entirely time constraints that have prevented me from
de-bitrotting this. I started a new job and haven't had time to bring this
up to date with mainline and the build system underwent some kind of change
around May/June that prevents the necessary headers from being generated. I
never got around to tracking down the issue. I'll take a look at it over
the next couple of weeks and let you know how much time/effort this is
going to take. I could definitely use some assistance from someone who
knows cmake and understands the build system.

Thanks,
Arjun

**Comment by autosquid** [comment]
hey! what are you doing!! we need this binding!

**Comment by autosquid** [comment]
hi, will this P.R. updated for opencv3?

**Comment by arjuncomar** [comment]
@autosquid: It's unlikely I'll have time to devote to de-bitrotting this project before the spring. Feel free to pick it up if you'd like to see it included.

**Pull request closed without merging**
