### PR TITLE
#18051 Fix CUDA GoodFeaturesToTrackDetector not threadsafe bug

### PR DESCRIPTION
**Pull request by nkwangyh**
resolves https://github.com/opencv/opencv/issues/18051

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

```
force_builders=Custom
buildworker:Custom=linux-4,linux-6
build_image:Custom=ubuntu-cuda:16.04
```

### CODE REVIEW

**Comment by nkwangyh** [comment]
original issue:CUDA GoodFeaturesToTrackDetector is not ThreadSafe ?
[issue](https://github.com/opencv/opencv/issues/18051)

**Comment by alalek** [comment]
@nkwangyh Thank you for contribution!

Please amend commit and remove `#` malformed reference from commit's message.
Also please check commit email - looks like it is not linked to your account (you may want to add secondary emails to GitHub profile)

**Comment by llschloesser** [comment]
It'd be nice to have the option for this algorithm to return `cv::KeyPoint`s with response and angle (even if set to 0 initially). `cv::cuda::FastFeatureDetector` should also fill that role, but it is broken, often never processing the bottom half of a given image.

**Comment by nkwangyh** [comment]
@alalek Sorry for the misoperations. I just tried to amend the commit but the pull request is closed unexpectedly. I have amended the commit message and recreated a new pull request. Here is the [link](https://github.com/opencv/opencv_contrib/pull/2868). I will update the reference in the issue and pull request.

**Comment by alalek** [comment]
replaced by #2868

**Pull request closed without merging**
