### PR TITLE
OCL: bioinspired: refactor OpenCL conditions

### PR DESCRIPTION
**Pull request by alalek**
https://github.com/opencv/opencv_contrib/pull/1318#issuecomment-342971194

### CODE REVIEW

**Comment by alalek** [comment]
@amroamroamro Could you check this with your case?

**Comment by alalek** [comment]
:+1:

**Comment by amroamroamro** [comment]
@alalek 
sorry it seems I never replied..
Yes the changes work for me (tested v3.4.0) 👍 

---

One comment, I can see you replaced `ocl::RetinaOCLImpl* _ocl_retina` with `cv::Ptr<ocl::RetinaOCLImpl> _ocl_retina`. Is it still correct to compare the smart pointer to 0? i.e shouldn't we do this:

    if (!_ocl_retina.empty()) ...

instead of this:

    if (_ocl_retina != 0) ...

or is there an implicit cast from `cv::Ptr` to the raw pointer?

**Comment by alalek** [comment]
Cast operator is here:
https://github.com/opencv/opencv/blob/3.4.0/modules/core/include/opencv2/core/cvstd.hpp#L373

but `.empty()` should be more clear.

**Comment by amroamroamro** [comment]
got it, thanks.

**Pull request merged**
