### PR TITLE
fix the bug that cannot detect multi qrcode when use_nn_detector is false

### PR DESCRIPTION
**Pull request by bit1002lst**
### Pull Request Readiness Checklist

related issus [#3343 3343](https://github.com/opencv/opencv_contrib/issues/3343)
See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by bit1002lst** [comment]
The change can be tested by the original test files. 
The test img should have two or more qrcode(such as
https://ts1.cn.mm.bing.net/th/id/R-C.fdec3dd2484aa10f9785cd460f17b418?rik=PaTvAy4%2b2VgBWA&riu=http%3a%2f%2fimg3.redocn.com%2ftupian%2f20150423%2ferweimashiliangsucai_4006416.jpg&ehk=KYk2bfwKcIwpF3fB45Aj2PhlwKhbJe8%2bgtHcEZC2CZk%3d&risl=&pid=ImgRaw&r=0) and set detector_prototxt_path / detector_caffe_model_path / super_resolution_prototxt_path / super_resolution_caffe_model_path is empty.

**Comment by AleksandrPanov** [comment]
@bit1002lst, need add test to approve PR

**Comment by asmorkalov** [comment]
OpenCV team uses GTest to implement unit tests and run them automatically. WeChat related tests are here: https://github.com/opencv/opencv_contrib/blob/4.x/modules/wechat_qrcode/test/test_qrcode.cpp. There is test for multiple qr codes, but it's disabled by some reason. @AleksandrPanov Please restore the test and they it could be extended to test both cases.

**Comment by asmorkalov** [comment]
@bit1002lst Could you rebase the patch on top of 4.x and fix the conflicts. Yet another patch for We chat module was just merged.

**Pull request closed without merging**
