### PR TITLE
Fixed issue 975 - fixed visual studio 2010 build errors on module xfeatures2d

### LINKED ISSUE #975: new errors on build in vs2010
##### System information (version)
- OpenCV => 3.2
- Operating System / Platform = Windows 32 Bit
- Compiler = Visual Studio 2010

##### Detailed description
Hi, I was trying to build opencv with xfeatures2d module while using Visual Studio 2010 and i got the following errors:
```
41>..\..\..\..\opencv_contrib\modules\xfeatures2d\src\pct_signatures.cpp(400): error C2668: 'cv::sqrt' : ambiguous call to overloaded function
41>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\math.h(589): could be 'long double sqrt(long double)'
41>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\math.h(541): or       'float sqrt(float)'
41>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\math.h(127): or       'double sqrt(double)'
41>          while trying to match the argument list '(const int)'

41>..\..\..\..\opencv_contrib\modules\xfeatures2d\src\harris_lapace_detector.cpp(107): error C2668: 'log' : ambiguous call to overloaded function
41>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\math.h(575): could be 'long double log(long double)'
41>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\math.h(527): or       'float log(float)'
41>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\math.h(120): or       'double log(double)'

41>..\..\..\..\opencv_contrib\modules\xfeatures2d\src\boostdesc.cpp(235): error C3861: 'round': identifier not found
```

I think these errors are caused by the use of an older C++ standard(C++98).

Does the opencv_contrib repository continues to follow the OpenCV Coding Style Guide (http://code.opencv.org/projects/opencv/wiki/Coding_Style_Guide)?

> ie: Formally, the code must comply with the C++ 98 standard

If so maybe this is an issue.

Also while I was searching for an already posted issue into this matter I noticed (https://github.com/opencv/opencv_contrib/issues/754) that deals with problems with builds with visual studio 2010. So i was wondering, is there an automatic build system for opencv that deals with this checks?

Thank you all in advance!

### PR DESCRIPTION
**Pull request by oqtvs**
### This pullrequest changes
Minor changes to fix visual studio 2010 build errors.
resolves #975

### CODE REVIEW

**Comment by alalek** [comment]
Thank you! :+1:

**Comment by oqtvs** [comment]
@alalek could you waiting longer for merging this PR? I've already tested it yesterday but i want to run more checks to verify if there are some differences between the round function and cvRound. Thanks

**Comment by oqtvs** [comment]
There is a difference between cvRound implementation as it uses "Round half to even" ie:
```
value: 2.5  c++11(round): 3 cvRound: 2
value: 4.5  c++11(round): 5 cvRound: 4
```
Also I searched opencv and opencv_contrib repositories for hand made implementations of rounding and I only found 3:

- https://github.com/opencv/opencv_contrib/blob/246ea8f3bdf174a2aad6216c2601e3a93bf75c29/modules/sfm/src/libmv_light/libmv/numeric/numeric.h

- https://github.com/opencv/opencv/blob/05b15943d6a42c99e5f921b7dbaa8323f3c042c6/modules/features2d/src/kaze/utils.h

- https://github.com/opencv/opencv_contrib/blob/bd619c55c1a0a0465d4c9458c3ec8ff1bf9709a4/modules/line_descriptor/src/binary_descriptor.cpp

As **cvRound** is the **most used** I would suggest keeping it. But also as this is my first PR I don't know the procedure here. Should I use some hand made implementation that mimics the behavior of c++11?

Thanks

**Comment by alalek** [comment]
@oqtvs Required tests are passed, so patch is valid. Thank you!

**Pull request merged**
