### PR TITLE
Updated samples/optflow/motempl.py file to solve 3 issues.

### PR DESCRIPTION
**Pull request by shaikmoeed**
**1)**  Resolved Syntax error at
 line 14: `def draw_motion_comp(vis, (x, y, w, h), angle, color):`
 by adding 
line 14: `def draw_motion_comp(vis, rect, angle, color):`
line 15:     `x, y, w, h = rect`

**2)** Resolved `TypeError: integer argument expected, got float`
Changed division to return integer value instead of float value
by changing from `/` to `//`.

**3)** Released `cam`  variable in a proper way by adding `.release()` method by which program is exiting properly. If `.release()` method is not added, even after destroying all windows program is not get closed.

### CODE REVIEW

**Comment by alalek** [comment]
As a "bugfix" this patch should [go](https://github.com/opencv/opencv/wiki/How_to_contribute#faq) into [3.4 branch](https://github.com/opencv/opencv/wiki/Branches) first.
We will merge changes from 3.4 into master regularly (weekly/bi-weekly).

So, please:
- change "base" branch of this PR: master => 3.4 (use "Edit" button near PR title)
- rebase your commits from master onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/master`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).
- push rebased commits into source branch of your fork (with `--force` option)

Note: no needs to re-open PR, apply changes "inplace".

**Comment by shaikmoeed** [comment]
@alalek  I have pushed changes to this `shaikmoeed:hotfix/samples-motempl-python-update`. Can you merge it to 3.4 branch?

**Comment by alalek** [comment]
Perhaps push operation was failed. Please ensure that you using `--force` option.

**Comment by shaikmoeed** [comment]
@alalek Sorry, I'm new to this rebase topic. 
Please check now. I have used `--force` to push my commits.

**Comment by shaikmoeed** [comment]
@alalek  Thank you so much for merging. This really motivates to contribute more from my side.

**Pull request merged**
