### PR TITLE
[GSoC 2019] Final: Information Flow Alphamatting

### PR DESCRIPTION
**Pull request by muskaankularia**
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/668

when this pullrequest gets merged, it
resolves #2240 

### This pullrequest changes

Implementation of "Designing Effective Inter-Pixel Information Flow for Natural Image Matting"

<cut/>

```
opencv_extra=master
```

### CODE REVIEW

**Comment by alalek** [comment]
> nanoflann

Why we can't use OpenCV's flann wrapper: https://github.com/opencv/opencv/tree/master/modules/flann ?

**Comment by muskaankularia** [comment]
> > nanoflann
> 
> Why we can't use OpenCV's flann wrapper: https://github.com/opencv/opencv/tree/master/modules/flann ?

I found nanoflann to be the most efficient library for KDTree implementation compared to openCV's KDTree. I didnt know about flann. If flann wrapper gives comparable/better result. I can replace nanoflann with flann's function call.

**Comment by sunitanyk** [comment]
@alalek , Not sure why the build bot is not getting the updated files. I tried doing
git clone -b alphamat https://github.com/muskaankularia/opencv_contrib.git
and I got a size of 180KB for the alphamat module. But it still shows a docs warning saying large patch size of 6 MB.

All other OS builds have successfully passed. Can Muskaan do anything more here to get the status to the PR to pass?

**Comment by alalek** [comment]
Git stores whole history, so "Delete ..." commits doesn't decrease total patch size.
You need to "squash commits onto one" for removing of intermediate changes.

**Comment by sunitanyk** [comment]
@alalek , This PR uses Eigen's Conjugate Gradient solver for sparse matrices. Is there anything in OpenCV for solving linear systems Ax=b using sparse matrices? Couldn't find any example or function for the same online in opencv docs. Please let me know.

**Comment by alalek** [comment]
@sunitanyk I believe there is no solver for sparse matrices in OpenCV.

You can continue using Eigen implementation, but related code should be properly excluded if build configuration doesn't have Eigen.

**Pull request closed without merging**
