### PR TITLE
Fast line detector

### PR DESCRIPTION
**Pull request by spacetrain**
A fast line detector. This detector runs up to two times faster than LSD while achieving competitive results.
Please evaluate it with ximgproc/samples/fld.lines.cpp.
A test code is also included to ximgproc/test/test_fld.cpp.

### CODE REVIEW

**Comment by alalek** [comment]
No need to reopen PR, just update your source branch.

Please rename/remove `fast_line_detector` branch in your opencv repository: https://github.com/spacetrain/opencv/branches

**Comment by spacetrain** [comment]
Great appreciation for the help from @alalek . Now it seems to be built fine.

**Comment by spacetrain** [comment]
I squashed multiple commits into one, and the code is now fixed.
Hope this can be merged... =)

**Comment by alalek** [comment]
Thank you! :+1:

**Comment by spacetrain** [comment]
Thanks a lot for your comments! @alalek

**Pull request merged**
