### PR TITLE
added multiple thinning algorithms

### PR DESCRIPTION
**Pull request by StevenPuttemans**
### This pullrequest changes

Added the option to choose which thinning algorithm you want to use

### CODE REVIEW

**Comment by alalek** [comment]
@StevenPuttemans Could you add some tests for this? Simple smoke tests without complex checks will be fine.
But I'm not sure about license of test image from previous PR.

**Comment by StevenPuttemans** [comment]
@alalek I might need some help here because

1) Tests are something completely new for me. Do you have any guides on how tests are made?
2) The test image that is inside the PR, is from the publicly available part of a fingerprint dataset, so I am pretty sure we can use it to illustrate the workings?

**Comment by alalek** [comment]
@StevenPuttemans 
1. Something like this: https://github.com/alalek/opencv_contrib/commits/pr874
2. Even public available datasets may have very restricted license.

BTW, There is GCC 6.2.1 warning:
```
/home/alalek/projects/opencv/contrib/modules/ximgproc/src/thinning.cpp: In function ‘void cv::ximgproc::thinningIteration(cv::Mat, int, int)’:
/home/alalek/projects/opencv/contrib/modules/ximgproc/src/thinning.cpp:53:27: warning: suggest parentheses around operand of ‘!’ or change ‘&’ to ‘&&’ or ‘!’ to ‘~’ [-Wparentheses]
                 int C  = (!p2 & (p3 | p4)) + (!p4 & (p5 | p6)) +
                           ^~~
/home/alalek/projects/opencv/contrib/modules/ximgproc/src/thinning.cpp:53:47: warning: suggest parentheses around operand of ‘!’ or change ‘&’ to ‘&&’ or ‘!’ to ‘~’ [-Wparentheses]
                 int C  = (!p2 & (p3 | p4)) + (!p4 & (p5 | p6)) +
                                               ^~~
/home/alalek/projects/opencv/contrib/modules/ximgproc/src/thinning.cpp:54:27: warning: suggest parentheses around operand of ‘!’ or change ‘&’ to ‘&&’ or ‘!’ to ‘~’ [-Wparentheses]
                          (!p6 & (p7 | p8)) + (!p8 & (p9 | p2));
                           ^~~
/home/alalek/projects/opencv/contrib/modules/ximgproc/src/thinning.cpp:54:47: warning: suggest parentheses around operand of ‘!’ or change ‘&’ to ‘&&’ or ‘!’ to ‘~’ [-Wparentheses]
                          (!p6 & (p7 | p8)) + (!p8 & (p9 | p2));

```

**Comment by StevenPuttemans** [comment]
@alalek I will take a look at the suggested PR, take a look at those warnings and fix them and will take a look at the license associated to the files. But making my own fingerprint image will be a bit more difficult, since I do not have a reader. Will take a look at what is possible and get back!

**Comment by StevenPuttemans** [comment]
Btw it seems that the buildbot just failed miserably xD but not due to my issue I guess

`/build/precommit-contrib_linux64/opencv_contrib/modules/dnn/3rdparty/protobuf/sources/protobuf-3.1.0/src/google/protobuf/descriptor.pb.cc:16026:1: fatal error: error writing to /tmp/ccIUBo4G.s: No space left on device
 }  // namespace google`

**Comment by alalek** [comment]
@StevenPuttemans Please remove extra empty line at the end of file:
```
modules/ximgproc/test/test_thinning.cpp:55: new blank line at EOF.
```

**Comment by StevenPuttemans** [comment]
Done :+1:

**Comment by StevenPuttemans** [comment]
@alalek what you think of adding a sample? Might be better to have a sample where the thinning is actually used? Like for example the segmentation of a blob and then skeletizing that one

**Comment by alalek** [comment]
Sure, you may also think about a tutorial that uses the sample.

:+1:

**Comment by StevenPuttemans** [comment]
Tutorial might be for later, no time for it now :)

**Comment by StevenPuttemans** [comment]
@alalek, is there any reason why samples in contrib do not allow the use of header `#include "opencv2/opencv.hpp"`?

**Pull request merged**
