### PR TITLE
Removed redundancies in the code

### LINKED ISSUE #2322: Redundancies in the code
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

This issue is associated with the code quality.
I observed some redundancies in [modules/face/src/face_alignmentimpl.hpp](https://github.com/opencv/opencv_contrib/blob/master/modules/face/src/face_alignmentimpl.hpp) and  [modules/face/src/face_utils.hpp](https://github.com/opencv/opencv_contrib/blob/master/modules/face/src/face_utils.hpp). I have described them below,

1. In [this line](https://github.com/opencv/opencv_contrib/blob/master/modules/face/src/face_alignmentimpl.hpp#L16) `using namespace std;` is used but still in the rest of the file, `std::` is written to specify the namespace. Probably, we can remove `using namespace std;`. 

2. Similarly, in [this line](https://github.com/opencv/opencv_contrib/blob/master/modules/face/src/face_utils.hpp#L10)  `using namespace cv;` is written and in the rest of the file, `cv::` is used to specify the namespace. 

Can I create a PR to resolve the above conflicts? Thanks.

### PR DESCRIPTION
**Pull request by czgdp1807**
resolves #2322 

### This pullrequest changes

This PR removes `using namespace std` and `using namespace cv` which were not required and were redundant. Please see the above issue for more details. 

```
force_builders_only=linux,docs
```

### CODE REVIEW

**Comment by czgdp1807** [comment]
I will take a look at the failures and fix them ASAP.

**Comment by czgdp1807** [comment]
I have updated the files. I will push the changes shortly. I am facing some problems related to dependencies, therefore, I am unable to build and test locally.

**Comment by czgdp1807** [comment]
Locally, VSCode wasn't showing any problems in the workspace. Let's see how the tests respond.

**Comment by czgdp1807** [comment]
The tests are passing. I don't know why they aren't updating here.

**Comment by alalek** [comment]
> were not required and were redundant

Obviously this is not true.

> +109 −121

Lets avoid unnecessary "cv::" and "std::" prefixes (we prefer to get rid of them).

In future please avoid large patches that didn't fix anything (in terms of functionality).
Closing for now.

**Pull request closed without merging**
