### PR TITLE
Wrap ICP for Python

### PR DESCRIPTION
**Pull request by Sahloul**
### This pullrequest changes

Exposes the `ICP` class to Python wrapper

### CODE REVIEW

**Comment by sovrasov** [comment]
@Sahloul could you add a minimalistic sample, which shows how to use the new bindings?

**Comment by Sahloul** [comment]
@sovrasov Although I am not happy with it, for now, I added something like a unit test to demonstrate its usage. In future however, I would like erase it and mimic the original C++ samples, but I need to wrap more functions first.

**Comment by Sahloul** [comment]
@alalek @vpisarev someone, kindly be asked to merge..

**Comment by Sahloul** [comment]
@alalek @vpisarev Kindly merge this PR since I was about making a mistake due to the similar branches I have.

**Pull request merged**
