### PR TITLE
Add calib3d module to Julia binding

### PR DESCRIPTION
**Pull request by archit120**
This PR adds support for the calib3d module in the Julia Bindings. The changelog also demonstrates the changes needed to wrap additional modules. I hope to add a blog post soon detailing this. 

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

```
allow_multiple_commits=1
```

### CODE REVIEW

**Review by vpisarev — APPROVED** [review]

**Comment by vpisarev** [comment]
@archit120, thank you! I finally reviewed it. @alalek, I pushed one more commit to archit120/julia_calib3d branch to fix one build problem with UsacParams and also did minor change in one of the examples. For some reason, this new commit does not show up here

**Comment by alalek** [comment]
There is incident on GitHub: http://status.github.com/
Need to wait for the service repair.

**Comment by vpisarev** [comment]
@alalek, thank you! Now the buildbot passed with one error in tracking module; I think, it's not related to the patch.

**Comment by archit120** [comment]
Thank you for the changes @vpisarev I had somehow not run into that error during my testing.

**Pull request merged**
