### PR TITLE
Example for plot module

### PR DESCRIPTION
**Pull request by LaurentBerger**
A sample for plot module : draw histogram

### CODE REVIEW

**Comment by sturkmen72** [comment]
it looks nice
but i did not understand
X=252
Y=12335 -> what does it mean ?
histogram_1

**Comment by LaurentBerger** [comment]
I think you remember http://answers.opencv.org/question/73233/how-do-you-plot-graphs-in-opencv-projects/#80870. @berak started a pr but he closed it. I wrote an example how to use this module and now I think a lot of work is necessary to really use this module...

**Comment by berak** [comment]
the numbers are [the coords of the last point of the curve](https://github.com/opencv/opencv_contrib/blob/master/modules/plot/src/plot.cpp#L330-L331) , whatever the author needed that for.

**Comment by sovrasov** [comment]
:+1:

**Comment by alalek** [comment]
@LaurentBerger Thank you! Could you please rebase your patch before merge? (to eliminate "merge" commit)

**Pull request closed without merging**
