### PR TITLE
Multithreading findScaleSpaceExtremaComputer in SIFT

### PR DESCRIPTION
**Pull request by woodychow**
There is one point about this change that I am not sure - Are stable keypoints needed? If not, the sort can be removed

I tried using thread local storage, keeping a vector of keypoints per thread and merge them at the end. It turned out that using a mutex is faster (i7 6700K). It might be slower on computers with 8 physical cores.

Needs https://github.com/opencv/opencv/pull/8820

### CODE REVIEW

**Comment by sovrasov** [comment]
@woodychow  To test this PR on Buildbot with https://github.com/opencv/opencv/pull/8815 you need to have the same branch name in the both PRs.

**Comment by woodychow** [comment]
Thanks. I just created a new PR to "opencv"
https://github.com/opencv/opencv/pull/8820

**Comment by woodychow** [comment]
@sovrasov, how can I trigger a rebuild?

**Comment by woodychow** [comment]
I am not sure why the code is stalling on Mac. I don't have a dev Mac machine at the moment.

**Comment by vpisarev** [comment]
:+1:

**Comment by woodychow** [comment]
Thanks!

**Pull request merged**
