### PR TITLE
Bioinspired module: fix some typos, add verbose option.

### PR DESCRIPTION
**Pull request by catree**
### This pullrequest adds

verbose option to avoid unnecessary prints. Some typos are also fixed.

@amroamroamro Can you test to see if the modifications did not break anything and solve your issue?

Related: [unnecessary print statements #7781](https://github.com/opencv/opencv/issues/7781)

### CODE REVIEW

**Comment by vpisarev** [comment]
@catree, thanks for the patch! I wonder if we can avoid adding verbose, and instead call printSetup() from the application after setup() is called?

**Comment by catree** [comment]
@vpisarev Indeed, your solution is better. I will revert the verbose changes and add a note in the documentation.

**Comment by amroamroamro** [comment]
@catree thanks for submitting a fix.
As vpisarev suggested, I don't think there is a need for "verbose" flag in the setup() functions. The API already provides public methods for that, so users are free to print the params themselves if they wish..

**Comment by catree** [comment]
I have reverted my changes and removed the printing. I have fixed some typos also.

**Comment by vpisarev** [comment]
thanks! :+1:

**Pull request merged**
