### PR TITLE
Exporting saliency classes to Python

### LINKED ISSUE #681: Dose module "saliency" work in python?
It does not seem like the "saliency" has python bindings.

I success build and import cv2 in python.
But "saliency" not work in python, though it work in c++.

This is very useful if it can use.

### PR DESCRIPTION
**Pull request by Ignotus**
resolves #681
The following proposed patch exports StaticSaliencySpectralResidual and MotionSaliencyBinWangApr2014 algorithms to Python.

```python
import cv2
img = cv2.imread('DSCF4494.JPG')
saliency = cv2.saliency.StaticSaliencySpectralResidual()
saliency.computeSaliency(img)
```

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
Just wondering if this is the complete saliency module. If not, are you maybe up to completely exporting the saliency module to python?

**Comment by Ignotus** [comment]
@StevenPuttemans no, it's not completed. Okay, I will come back with a new commit :)

**Comment by StevenPuttemans** [comment]
it might be better to incorporate everything into a single PR and just push your updates to this branch so your PR gets updated too.

**Comment by sovrasov** [comment]
@Ignotus what's the current status of PR?

**Pull request closed without merging**
