### PR TITLE
Re-write surface matching using vectors and matrices

### PR DESCRIPTION
**Pull request by terfendail**
Recreated #1023 by @Sahloul:

Code rebased to latest master to handle merge conflicts

Original PR description

This is supposed to increase efficiency, readability, maintainability, and support Python bindings.

### This pullrequest changes
- Rewrites the surface matching module using `cv::Matx` and `cv::Vec`
- Utilize the OpenCV utilities to reduce the code size
- All `unsigned type` have been rewritten to `utype`
- Some complex expressions or resource intense functions are simplified

During the reduction process, no functionality was harmed, and all samples have been tested.

### CODE REVIEW

**Comment by bmagyar** [comment]
Still :+1:

Do you also have numbers on execution speed we could compare?

**Comment by terfendail** [comment]
@bmagyar No, I don't estimate performance of the updated code. I've just rebased it to make PR merge possible. I don't think the change could decrease performance, so IMHO python bindings added by PR worth it to be merged.

**Comment by terfendail** [comment]
This PR depends on Matx and Vec python wrappers added in [opencv#9839](https://github.com/opencv/opencv/pull/9839)

**Comment by vpisarev** [comment]
looks great, thank you, Vitaly! :+1:

**Comment by Sahloul** [comment]
@terfendail Thank you for the recreation!
I have mixed feelings now, happy that surface matching will get better, and sad that my three days work will not appear as my own one in the commit history!

**Comment by alalek** [comment]
@Sahloul Thank you for great effort!
Commit author is still you, so your name will be in Git history:
```
commit 2cfc35317260f57caec5a7ed4df71f43cda028f3 (HEAD)
Author: Hamdi Sahloul <hamdisahloul@hotmail.com>
Date:   Fri Feb 24 01:16:16 2017 +0900

    Re-write surface matching using vectors and matrices
```

Anyway you could re-open and rebase your original PR.

**Comment by Sahloul** [comment]
I have no problem then ;)

**Comment by bmagyar** [comment]
Thanks for the effort guys!

**Pull request merged**
