### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by sturkmen72**
### This pullrequest changes
sets ` -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF`
to avoid time out of Travis CI

actually it gives
> The job exceeded the maximum time limit for jobs, and has been terminated.

### CODE REVIEW

**Comment by asmorkalov** [comment]
@alalek Is Travis-CI used somehow for validation?

**Comment by alalek** [comment]
We don't use Travis for OpenCV repositories

**Comment by alalek** [comment]
BTW,

Probably it would be nice to add `BUILD_EXAMPLES=ON`

> make -j5

Not sure that Travis allows multiple cores per Job on free accounts. Oversubscribing will cause terrible results.
Does `make -j$(nproc)` work?
Or we can switch to ninja build tool (`cmake -GNinja ...` + `ninja`)

**Comment by asmorkalov** [comment]
The default host configuration for travis is 2-cores WM. So `-j5` is redundant.

**Comment by sturkmen72** [comment]
> Probably it would be nice to add BUILD_EXAMPLES=ON

i think this will cause timeout again

another issue is indeed OpenCV 3.4 branch should be cloned in  Contrib 3.4 branch  and OpenCV master branch should be cloned in  Contrib master branch

**Comment by alalek** [comment]
`git clone --branch 3.4 --depth=1 https://github.com/opencv/opencv.git`

**Pull request merged**
