### PR TITLE
Features/python wrapper/rgbd - some functions

### PR DESCRIPTION
**Pull request by Sahloul**
### This pullrequest changes

Provides Python wrapper for `cv2.rgbd.depthTo3d()` and `cv2.rgbd.warpFrame()` functions.

### CODE REVIEW

**Comment by alalek** [comment]
Could you please squash all these commits into one?

**Comment by Sahloul** [comment]
@alalek, after squash, repo went in limbo! I will create a new pull...

**Comment by alalek** [comment]
BTW, Squashed "backup" is [here](https://github.com/alalek/opencv_contrib/commits/pr990)

**Comment by Sahloul** [comment]
Could you then merge from your backup, or the new pull request?

**Pull request closed without merging**
