### PR TITLE
How to find the files for facemark->load model?

### PR DESCRIPTION
**Pull request by hsmlee**
bool myDetector(cv::InputArray image, cv::OutputArray faces, cv::CascadeClassifier *face_cascade){
   cv::Mat gray;

   if (image.channels() > 1)
       cvtColor(image, gray, CV_BGR2GRAY);
   else
       gray = image.getMat().clone();

   equalizeHist(gray, gray);

   std::vector<cv::Rect> faces_;
   face_cascade->detectMultiScale(gray, faces_, 1.4, 2, cv::CASCADE_SCALE_IMAGE, cv::Size(30, 30));
   cv::Mat(faces_).copyTo(faces);
   return true;
}

- (UIImage *) detectFacialLandmark:(UIImage *) image{
   double CurrentTime = CACurrentMediaTime();
   
   NSString *pathToFaceCascade = [[NSBundle mainBundle] pathForResource:@"lbpcascade_frontalface" ofType:@"xml"];
   
   cv::Mat faceImage;
   UIImageToMat(image, faceImage);
   
   cv::CascadeClassifier face_cascade;
   face_cascade.load([pathToFaceCascade UTF8String]);
   cv::face::FacemarkKazemi::Params params;
   cv::Ptr<cv::face::FacemarkKazemi> facemark = cv::face::FacemarkKazemi::create(params);
   facemark->setFaceDetector((cv::face::FN_FaceDetector)myDetector, &face_cascade);
   facemark->loadModel("load model");
   std::vector<cv::Rect> faces;
   resize(faceImage,faceImage,cv::Size(460,460), 0, 0, cv::INTER_LINEAR_EXACT);
   facemark->getFaces(faceImage,faces);
   std::vector< std::vector<cv::Point2f> > shapes;
   if(facemark->fit(faceImage,faces,shapes))
   {
       for( size_t i = 0; i < faces.size(); i++ )
       {
           cv::rectangle(faceImage, faces[i], cvScalar(255, 0, 0));
       }
       for(unsigned long i=0;i<faces.size();i++){
           for(unsigned long k=0;k<shapes[i].size();k++)
               cv::circle(faceImage,shapes[i][k],5,cv::Scalar(0,0,255),cv::FILLED);
       }
   }
   
   
   UIImage *returnImage = MatToUIImage(faceImage);
   NSLog(@"test processing time : %f", (CACurrentMediaTime() - CurrentTime));
   
   return returnImage;
}

I'm doing the project for the iOS application.
For this project, I'm using OpenCV. Specifically, I added OpenCV_contrib modules to obtain the information of face landmarks.

During applied OpenCV_contrib, I have met one problem.
facemark->loadModel("load model"); 
For detecting the facemark, I have to find the model files.

I wonder that how can I find the model files for "facemark->loadModel("load model"); "

### CODE REVIEW

**Comment by csukuangfj** [comment]
In this [tutorial code][1]:

```.cpp
CascadeClassifier face_cascade;
```

This [line][2]
```.cpp
    if( !face_cascade.load( face_cascade_name ) ){ printf("--(!)Error loading face cascade\n"); return -1; };
```

where the model file is at <https://github.com/opencv/opencv/tree/master/data/haarcascades>

Maybe this is what you want.

[2]: https://github.com/opencv/opencv/blob/master/samples/cpp/tutorial_code/objectDetection/objectDetection.cpp#L37
[1]:
https://github.com/opencv/opencv/blob/master/samples/cpp/tutorial_code/objectDetection/objectDetection.cpp#L15

**Comment by hsmlee** [comment]
It seems that is for detecting the face.
Actually, we are finding the model file for the 68 facemarks.

I wonder how can I call "FacemarkKazemi->loadModel();"

**Comment by csukuangfj** [comment]
You can try this model

<https://github.com/opencv/opencv_3rdparty/blob/8afa57abc8229d611c4937165d20e2a2d9fc5a12/face_landmark_model.dat>

I think it is specific for `FacemarkKazemi`

**Comment by hsmlee** [comment]
Hello!

 I really appreciate you replying to me in a prompt way.

I have tried https://github.com/opencv/opencv_3rdparty/blob/8afa57abc8229d611c4937165d20e2a2d9fc5a12/face_landmark_model.dat

It works, but I think it detects wrong facemarks.

I uploaded the question and image on https://stackoverflow.com/questions/48080914/what-model-is-needed-to-detect-facemark-by-using-opencv-contrib

I would really appreciate your help!

**Comment by csukuangfj** [comment]
Perhaps you have to use some training images to refine the model.

The samples in this [test file][1] may be helpful.

[1]: https://github.com/opencv/opencv_contrib/blob/master/modules/face/test/test_face_align.cpp#L44

**Pull request closed without merging**
