### PR TITLE
fix link for thinningTypes

### PR DESCRIPTION
**Pull request by StevenPuttemans**
broken link fixed

### CODE REVIEW

**Comment by alalek** [comment]
:+1:

**Comment by StevenPuttemans** [comment]
Thx!

**Comment by StevenPuttemans** [comment]
@alalek any idea when hitting the ximgproc module, why the types are not showing on top? They are in the same header file right?

**Comment by StevenPuttemans** [comment]
http://pullrequest.opencv.org/buildbot/export/pr_contrib/934/docs/df/d2d/group__ximgproc.html

**Pull request merged**
