### PR TITLE
Adding hfs segment module

### PR DESCRIPTION
**Pull request by Yujun-Shi**
adding a very efficient algorithm for image segmentation called hfs

### CODE REVIEW

**Comment by sturkmen72** [comment]
@alalek what is the problem about builtbot on this PR?
( @Yujun-Shi asked on [answers.opencv.org](http://answers.opencv.org/question/176606))

**Comment by alalek** [comment]
Source branch name is "master" here. There are some testing problems (related to opencv_extra) so automatic tests are disabled completely for such branches.
It is better to use meaningful names for branches like "segmentation_hfs".

**Comment by Yujun-Shi** [comment]
many thanks, you guys!!!

**Comment by Yujun-Shi** [comment]
This pull request is closing because it can't be rerun

**Pull request closed without merging**
