### PR TITLE
Add short tutorial for FSR-based image inpainting

### PR DESCRIPTION
**Pull request by si40wiga**
### This pullrequest changes
adds tutorial for #2296

### CODE REVIEW

**Comment by alalek** [comment]
Thank you for contribution!

Usually we using JPEG images in documentation for real-life images.
Lossless PNG format is used for tests (or for diagrams / masks).

Also original image is stored twice (approach with 3 images would be better).

Could you please convert used images into JPEG format?
In case of non-acceptable artifacts, please use some image patch (ROI) in PNG format to show algorithm results (up to 64x64, you may upscale it by x4/x8).

**Comment by asmorkalov** [comment]
@si40wiga Friendly reminder.

**Comment by alalek** [comment]
You need to squash commits into one (we don't need full history of changes here - git still stores .png files).

**Comment by si40wiga** [comment]
Thanks! I hope it's fine now.

> Also original image is stored twice (approach with 3 images would be better).
I'm a bit confused because I didn't store the original image twice. The reconstruction image shows the results with the two different quality profiles. The differences between the profiles are still visible in jpg format (e.g. at the front edge of the roof).

**Pull request merged**
