### PR TITLE
Add surface_matching module.

### PR DESCRIPTION
**Pull request by bmagyar**
This is the surface_matching module developed by @tolgabirdal for the GSoC 2014.

Video can be found [here](https://www.youtube.com/watch?v=uFnqLFznuZU)

### CODE REVIEW

**Comment by patrycjabb** [comment]
Hi! I was trying to run surface_matching module, but I get an error when running with sample data: 

"Run-Time Check Failure #2 - Stack around the variable 'hashKey' was corrupted."

It's at the beginning - training step.
Can anyone help?

**Comment by tolgabirdal** [comment]
Please define the keytype as follows:

#if (defined x86_64 || defined _M_X64)
#include 
typedef uint64_t KeyType;
#else
typedef unsigned int KeyType;
#endif

This will be fixed.

All the bests,

**Comment by patrycjabb** [comment]
Thank you!

I fixed it by replacing "murmurHash" with "hashMurmurx86", as written here https://github.com/Itseez/opencv_contrib/issues/170

**Comment by JoyMazumder** [comment]
Hello, I am new at C++. Can you tell me in which file I should add those lines? Thank you

**Pull request merged**
