### PR TITLE
try to solve issue #8748

### PR DESCRIPTION
**Pull request by LaurentBerger**
Try to solve issue #8748 and update sfm doc for windows

### CODE REVIEW

**Comment by sovrasov** [comment]
:+1:

**Comment by PhilLab** [comment]
@LaurentBerger out of curiosity: which issue did you mean?

**Comment by PhilLab** [comment]
@LaurentBerger out of curiosity: which issue did you mean?

**Comment by LaurentBerger** [comment]
@PhilLab this one https://github.com/opencv/opencv/issues/8748

**Pull request merged**
