### PR TITLE
TLD with parallel_for_ (targeting TBB enabled builds)

### PR DESCRIPTION
**Pull request by TheDZhon**

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
Do squash your commits into 1! That being said :+1: for the update!

**Comment by TheDZhon** [comment]
Thank you for commenting!
It's done.

**Comment by sovrasov** [comment]
:+1:

**Comment by sovrasov** [comment]
FYI: [benchmark sample output](https://gist.github.com/sovrasov/9e92a24c45bd0690890d6a40fd0a9c83)

**Comment by TheDZhon** [comment]
Ok, I think that problem is solved: standardPatches std::vector used copy-cted Mat_ instances with resize call. The instances is reference counted and uses same memory after all.

New version explicitly clones Mat_ instances with standardPatches growth. Parallel section body now enlarged with resample calls.

**Comment by sovrasov** [comment]
With the last update performance has decreased comparing to previous parallel code, but results are more stable. :+1:  again

**Pull request merged**
