### PR TITLE
New functionality and optimization for the Saliency module

### PR DESCRIPTION
**Pull request by fpuja**
From the last pull request, I added new functionality and I optimized different parts of the code:

new functionality: 
- noise control
- perf test for motionSaliencyBinWangApr2014
- perf test for staticSaliencySpectralResidual
- perf test for objectnessBING

optimization: 
- i converted all possible matrices to CV_8U, so as to speed up computation
- i implemented a new sorting algorithm, more optimized

### CODE REVIEW

**Comment by Dikay900** [comment]
Since noone wrote here yet.
* First things first please rewrite your formatting using 4 whitespaces for one indent not 2 whitespaces
* please see the warnings on the windows build machine and try to fix them: http://pullrequest.opencv.org/buildbot/builders/precommit-contrib_windows64/builds/555/steps/compile%20release/logs/warnings%20%288%29
* someone else has to review the functionality maybe additional notes will be added by others

**Comment by fpuja** [comment]
Hi @Dikay900, 

I have solved all the windows warning, all the builds now are ok. I have solved also the open issues. I think the code is now ready to be merged.

**Comment by Dikay900** [comment]
an opencv developer has to review this commit to get this merged. Could take some time on this repo. Please be patient.

**Comment by fpuja** [comment]
I know it @Dikay900 , is not my first pull request. :) What I wrote before means that for me it's ok, based on the opencv guidelines and my little experience, and I am therefore open to further suggestions if it does not go well.

**Pull request closed without merging**
