### PR TITLE
balanceWhite fixed maxValue bin search

### LINKED ISSUE #154: Problem outputMin outputMax in balanceWhite
After processing balanceWhite (xphoto /src/simple_color_balance.cpp), the values of the matrix it can not go into the range [outputMin, outputMax]

```
   Mat test(3,3,CV_32FC1);
    test.at<float>(0, 0) = 21000;
    test.at<float>(0, 1) = 24000;
    test.at<float>(0, 2) = 20000;
    test.at<float>(1, 0) = 21000;
    test.at<float>(1, 1) = 20000;
    test.at<float>(1, 2) = 20000;
    test.at<float>(2, 0) = 23000;
    test.at<float>(2, 1) = 20000;
    test.at<float>(2, 2) = 10000;
    double min1, max1;
    cv::minMaxIdx(test, &min1, &max1);
    cv::xphoto::balanceWhite(test, test,
                             cv::xphoto::WHITE_BALANCE_SIMPLE,
                             min1, max1,
                             0, 65536);
    cv::minMaxIdx(test, &min1, &max1);
```

In this example max1 = 76889.9 (mingw4.8.2)
When working with large matrices can greatly values go into the negative numbers
Thanks!

### PR DESCRIPTION
**Pull request by lukaszi89**
**Merge with extra**: https://github.com/Itseez/opencv_extra/pull/293

Fixed bug for histogram p2 bin index and maxValue search.

resolves #154

### CODE REVIEW

**Comment by lukaszi89** [comment]
require test data update (verification results) from issue 292 from opencv_extra repo
https://github.com/Itseez/opencv_extra/pull/292

**Comment by lukaszi89** [comment]
unsuccessful build due to large image changes in opencv_extra?

**Comment by alalek** [comment]
Yes, it is a warning

**Comment by sovrasov** [comment]
@lukaszi89 could you resolve the merge conflict?

**Pull request closed without merging**
