### PR TITLE
solve issue #853

### PR DESCRIPTION
**Pull request by LaurentBerger**
Using eigen 3.3 on windows with vs 2015 constant M_Pi is undefined now . Add compilation directive _USE_MATH_DEFINES solves this problem
I have modified multiview cmakelists to check eigen version

### CODE REVIEW

**Comment by sovrasov** [comment]
Strange, I have no problems with the latest Eigen master on Ubuntu 16.04.

**Comment by LaurentBerger** [comment]
@sovrasov  I don't use Ubuntu. I use vs 2015 with opencv 3.3

Origin is  this commit https://bitbucket.org/eigen/eigen/commits/0dfb2d5d3d33d9c44b5cfbd6c5fb68768c05c88a#general-comments

**Comment by alalek** [comment]
Probably it is better to add this define globally. @LaurentBerger Could you check https://github.com/opencv/opencv/pull/8001 please?

**Comment by terfendail** [comment]
Agree with @alalek 
Since M_PI issue on VS2015 is generic it could later raise in another module so I also consider it better option to fix it globally

**Comment by LaurentBerger** [comment]
I think that @alalek solution is  better than mine so we can close this issue

**Pull request closed without merging**
