### PR TITLE
[ISCAS] loadPLYSimple return Zero Mat after reading PLY file

### PR DESCRIPTION
**Pull request by TachikakaMin**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

Function Doc: https://docs.opencv.org/master/d9/d25/group__surface__matching.html#gad893719cc47a72b24482f2bfdebb409e

This function will return a zero Mat after it reads .ply file. 

Example File: https://www.artec3d.com/3d-models/vw-bus#download

### CODE REVIEW

**Comment by alalek** [comment]
OpenCV loader expects text format only.

> format ascii 1.0

Your file is in binary format:

> format binary_little_endian 1.0


So this patch is not complete.
- determine format properly. throw error in case of unknowns
- add dedicated loader for binary data (with proper processing of little-endian / big-endian byte orders)

**Comment by TachikakaMin** [comment]
Oh, that's true. I will do it later.

**Comment by mihaibujanca** [comment]
@TachikakaMin The title of the PR and the content don't match. There should be a PR for the `loadPLYSimple` problem, but the commits relate to the planar simplification project.

**Comment by vpisarev** [comment]
@TachikakaMin, @mihaibujanca; let me close this pull request; the code needs a substantial rewrite. If/when it's done, feel free to reopen this PR or create a new one

**Pull request closed without merging**
