### PR TITLE
Add semantic segmentation to the module DNN.

### PR DESCRIPTION
**Pull request by vbystricky**
Add Crop and Eltwise layers. 
Add sample for using FCN32s or FCN8s neural network for image semantic segmentation.

### CODE REVIEW

**Comment by vpisarev** [comment]
@vbystricky, if you have time, could you please re-base your PR?

**Comment by vbystricky** [comment]
@vpisarev I will make re-base, but I think we have to fix problems with convolution and deconvolution layers code first. Because segmentation code fails on current implementation.

**Comment by vbystricky** [comment]
@vpisarev rebased. But sample fcn_semsegm crashes because a problem in deconvolution layer.

**Comment by vpisarev** [comment]
ok, let's put it in and then make it work! :+1:

**Pull request merged**
