### PR TITLE
add in option to show points only for plot module

### PR DESCRIPTION
**Pull request by jasjuang**
In order to solve https://github.com/Itseez/opencv_contrib/issues/581

If the input of setPlotLineWidth is not larger than zero, show data as points only instead of connecting them to form a line

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
Could you also document this option in the function description?

**Comment by jasjuang** [comment]
could you let me know where exactly should I add the documentation? Is it plot.hpp?

**Comment by StevenPuttemans** [comment]
Sorry for the delay, kind of forgot about this. Yes documentation goes above functions inside the header file. So indeed, you need to update plot.hpp to incorporate information about this.

**Comment by jasjuang** [comment]
Just to make sure I am looking at the right file, is it opencv_contrib/modules/plot/include/opencv2/plot.hpp that I should update? The weird part is there is no documentation for the original functions

**Comment by StevenPuttemans** [comment]
Ow that is actually correct ... http://docs.opencv.org/master/d0/d1e/classcv_1_1plot_1_1Plot2d.html#gsc.tab=0

Would you mind adding documentation for the complete plot module if you are up to it?  And yes that is the file. It should start to look like other classes, e.g. https://github.com/Itseez/opencv_contrib/blob/master/modules/aruco/include/opencv2/aruco.hpp

If not give me a shout and I will add docs for those classes!

**Comment by jasjuang** [comment]
I prefer not to add the entire documentation because I am not familiar with the entire code. Please go ahead and do it!

**Comment by StevenPuttemans** [comment]
I will add it to my todo list!
@nmoutinho are you maybe up to helping us out with some documentation on the main plot module?

**Comment by nmoutinho** [comment]
Hi @StevenPuttemans. I'll do that. No problem ;)

**Comment by StevenPuttemans** [comment]
@nmoutinho thank you for doing that!

**Comment by sovrasov** [comment]
Replaced by #787

**Pull request closed without merging**
