### PR TITLE
fix the bug that cannot detect multi qrcode when use_nn_detector is false

### PR DESCRIPTION
**Pull request by bit1002lst**
A new PR based on the top of 4.x and fix the conflicts
related issus https://github.com/opencv/opencv_contrib/issues/3343

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by bit1002lst** [comment]
I found there is build fail when decode test case [3_close_qrcodes.png]. 
May I fix this? I cannot find the test image

**Comment by bit1002lst** [comment]
@AleksandrPanov

**Comment by AleksandrPanov** [comment]
@bit1002lst, 3_close_qrcodes.png (from opencv_extra):

3_close_qrcodes

**Comment by bit1002lst** [comment]
@AleksandrPanov  Hello, I have tested this image and recurrent this error.
But, actually, this error is not caused by this PR, because it still exist in top 4.x versions.

**Comment by AleksandrPanov** [comment]
@asmorkalov, could you check PR?

**Comment by bit1002lst** [comment]
> @bit1002lst, you broke tests with `use_nn_detector = true` by adding duplicate qr corners to answer
> 
> fixed by this commit: [fixed duplicate corners and style](https://github.com/opencv/opencv_contrib/pull/3351/commits/14157b140ea83777dede37cd7dbeb75c64fc7a7a)
> 
> also added test with [multi detect](https://github.com/opencv/opencv_contrib/pull/3351/commits/cfcfd5f4114a6014d93345a82ea397c2cc1aeb40)

Thanks for your help

**Review by AleksandrPanov — APPROVED** [review]

**Review by Gitgody — COMMENTED** [review]
exit

**Pull request merged**
